### ISSUE TITLE
build.gradle.kts requires explicitly java11

### ISSUE THREAD

**Issue by igalshilman** [restatedev/e2e#237]
This requires the presence of exactly `jdk11`, which is becoming less and less likely as it was EOLed, let's at least use 17.

**Comment by slinkydeveloper** [comment]
> This requires the presence of exactly jdk11, which is becoming less and less likely as it was EOLed, let's at least use 17.

Can you post the error?  On my machine I use jdk 17 and i never stumbled upon an error related to wrong jdk. Only target/source compatibility is jdk 11, but everything above it should work fine.

**Comment by tillrohrmann** [comment]
I am using jdk 20 and it works for me locally.

**Comment by slinkydeveloper** [comment]
> Are you folks sure that you don't have jdk11 hanging around?

I do have a jdk11 on my machine... Maybe you're right it's picking that up. Although that's very strange behavior on gradle, why is it requiring a specific jdk? Will investigate that.

**Comment by slinkydeveloper** [comment]
> This might be a bit more relevant for the java sdk, i wouldn't worry about this too much here.

Do you experience the same problem in the java sdk?

Also I think it's important that everyone of us is able to run e2e tests without problems :)

**Comment by tillrohrmann** [comment]
I do have an JDK 11 on my machine as well.

**Comment by tillrohrmann** [comment]
> Changing this value to 17 worked for me, i can continue doing that every time I need to run these tests locally.

Let's definitely not do this but fix it properly so that everyone can run the e2e tests.

**Comment by AhmedSoliman** [comment]
I have a somewhat similar issue. 

Platform: MacOS 14.2.1 (aarch64)
```sh
❯ java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
```

```sh
❯ /usr/libexec/java_home
/opt/homebrew/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home
```

On a newly initialized gradle project (created with gradle 8.5). I can query installed toolchains
```sh
❯ gradle -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Amazon Corretto JDK 20.0.2.1+10-FR
     | Location:           /Users/asoli/Library/Java/JavaVirtualMachines/corretto-20.0.2.1/Contents/Home
     | Language Version:   20
     | Vendor:             Amazon Corretto
     | Architecture:       aarch64
     | Is JDK:             true
     | Detected by:        IntelliJ IDEA

 + Homebrew JDK 21.0.1
     | Location:           /opt/homebrew/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home
     | Language Version:   21
     | Vendor:             Homebrew
     | Architecture:       aarch64
     | Is JDK:             true
     | Detected by:        Current JVM
```

When running `./gradlew` (even if I update our gradle version from 8.4 to 8.5) I get this error:
```sh
❯ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'restate-e2e'.
> Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
   > No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.4/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.4/userguide/toolchains.html#sub:download_repositories.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 524ms
```
