### ISSUE TITLE
can't build e2e tests

### ISSUE THREAD

**Issue by igalshilman** [restatedev/e2e#238]
Looking at the current main branch.

```
> Task :tests:compileTestKotlin FAILED
e: file:/// .../tests/src/test/kotlin/dev/restate/e2e/node/EmbeededHandlerApiTest.kt:29:37 Unresolved reference: getRestateEnvironment
```

cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
I'm sorry, I'm not sure how to help judging from only this message. The code is correct, on my machine compiles fine and it does on CI scheduled jobs https://github.com/restatedev/e2e/actions

**Comment by slinkydeveloper** [comment]
Perhaps you're trying to compile a submodule first before the parent? (although gradle should correctly compile the parent as well)

**Comment by slinkydeveloper** [comment]
Can I close this?
