### ISSUE TITLE
Node Dockerfile leaks secrets

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/e2e#87]
Our Node [Dockerfile](https://github.com/restatedev/e2e/blob/bf866e61fcf41aa7727511aae9f3b74710353ca7/services/node-services/Dockerfile) accepts the `NPM_TOKEN` as a build arg. That way it will be recorded in the history of the image and others can retrieve the secret. It would be better to use `--mount=type=secret,id=NPM_TOKEN` to mount a secret. However, so far I couldn't find a way to provide the secret to the build process. It seems that this is not supported by the [Gradle Docker plugin](https://github.com/bmuschko/gradle-docker-plugin) we are using.

**Comment by slinkydeveloper** [comment]
no more secrets these days :)
